# Context path for the application as a whole
server.servlet.context-path=/
# Database connection setup
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/chatgc
spring.datasource.username=postgres
spring.datasource.password=0000
# Database platform configuration for Eclipselink
spring.jpa.database-platform=org.eclipse.persistence.platform.database.PostgreSQLPlatform
# Additional database-access specifics
spring.jpa.generate-ddl=true
spring.jpa.show-sql=false
# application.properties allows to configure many more application parameters
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=test.meeting.scheduler@gmail.com
spring.mail.password=fnkkumefjbvirbst
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true


